# Generated by Django 6.0.3 on 2026-03-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_shop', '0003_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
